% Description: this function predicts using support vector regression model

% Author: Victor Sellemi

% INPUT: 
%        - Xte    = (n x k) matrix of predictors
%        - model  = SVR structure as generated by 'train_SVR.m'
% OUTPUT: 
%        - alpha  = (n x 1) vector 


function yhat = forecast_SVR(Xte,model)

    kernel = model.kernel;
    Xtr    = model.X; 
    alpha  = model.alpha;
    b      = model.b;
    sigma  = model.sigma;

    Ntr = size(Xtr,1);
    Nte = size(Xte,1); 
    K = zeros(Nte, Ntr); 

    switch kernel 
        case 'gaussian'
            XXh1 = sum(Xtr.^2,2) * ones(1,size(Xte,1));
            XXh2 = sum(Xte.^2,2) * ones(1,size(Xtr,1));
            D  = XXh1 + XXh2' - 2*Xtr*Xte';
            K = exp(-D/(2*sigma^2))';
        case 'linear'
            K = Xte * Xtr';
        case 'poly2'
            K = (Xtr * Xtr').^2;
        case 'poly3'
            K = (Xtr * Xtr').^3;
        case 'sigmoid'
            K = tanh(Xtr * Xtr');
    end
    
    yhat = K*alpha + b; 
     
    
end